package com.kadaiku.brunei

import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import coil.compose.rememberAsyncImagePainter
import kotlinx.coroutines.delay
import java.util.Calendar
import java.util.UUID

data class SellerProfile(val shop:String,val phone:String,val address:String)
data class Product(val id:String=UUID.randomUUID().toString(),val name:String,val price:Double,val shop:String,val category:String,val area:String,val image:String,val sellerPhone:String,val sellerAddress:String)
data class CartLine(val product:Product,var qty:Int)
data class Order(val id:String=UUID.randomUUID().toString().take(8).uppercase(),val lines:List<CartLine>,val delivery:String,val total:Double,val createdAt:Long=System.currentTimeMillis())

@Composable fun money(v:Double)=Text("B$%.2f".format(v))

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{KadaiKuApp()}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun KadaiKuApp(){
    var tab by remember{mutableIntStateOf(0)}
    var products by remember{mutableStateOf(listOf(
        Product(name="Kek Coklat Premium",price=15.0,shop="Dapur Aisyah",category="Makanan",area="Gadong",image="🍰",sellerPhone="+673 7XX XXXX",sellerAddress="Gadong, Brunei-Muara"),
        Product(name="Perfume Oud",price=20.0,shop="Brunei Fragrance",category="Beauty",area="Kiulap",image="🧴",sellerPhone="+673 8XX XXXX",sellerAddress="Kiulap, Brunei-Muara"),
        Product(name="Baju Melayu",price=35.0,shop="Kedai Kita",category="Fashion",area="Bandar",image="👕",sellerPhone="+673 7XX XXXX",sellerAddress="Bandar Seri Begawan"),
        Product(name="Frozen Food Combo",price=12.0,shop="Mama's Frozen",category="Makanan",area="Tutong",image="🥟",sellerPhone="+673 8XX XXXX",sellerAddress="Tutong, Brunei")
    ))}
    var cart by remember{mutableStateOf(listOf<CartLine>())}
    var orders by remember{mutableStateOf(listOf<Order>())}
    var search by remember{mutableStateOf("")}
    var showSeller by remember{mutableStateOf(false)}
    var showAdd by remember{mutableStateOf(false)}
    var sellerProfile by remember{mutableStateOf(SellerProfile("Kedai Saya","",""))}
    val filtered=products.filter{search.isBlank()||it.name.contains(search,true)||it.shop.contains(search,true)||it.category.contains(search,true)}
    Scaffold(topBar={CenterAlignedTopAppBar(title={Text("KadaiKu 🇧🇳",fontWeight=FontWeight.Bold)})},bottomBar={NavigationBar{listOf("Home","Search","Cart (${cart.sumOf{it.qty}})","Profile").forEachIndexed{i,l->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={},label={Text(l)})}}}){pad->
        when(tab){
            0->Home(filtered,search,{search=it},{showSeller=true},{p->cart=addCart(cart,p)},Modifier.padding(pad))
            1->SearchPage(filtered,search,{search=it},{p->cart=addCart(cart,p)},Modifier.padding(pad))
            2->CartPage(cart,{p->cart=removeOne(cart,p)},{p->cart=addCart(cart,p)},{delivery,total->if(cart.isNotEmpty()){orders=orders+Order(lines=cart.map{it.copy()},delivery=delivery,total=total);cart=listOf();tab=3}},Modifier.padding(pad))
            else->ProfilePage(orders,{showSeller=true},Modifier.padding(pad))
        }
    }
    if(showSeller)SellerSheet(onClose={showSeller=false},onAdd={showAdd=true},products=products,orders=orders,profile=sellerProfile,onProfileChange={sellerProfile=it},onDelete={id->products=products.filterNot{it.id==id}})
    if(showAdd)AddProductDialog(sellerProfile=sellerProfile,onDismiss={showAdd=false},onSave={name,price,cat,area,image->products=products+Product(name=name,price=price,shop=sellerProfile.shop.ifBlank{"Kedai Saya"},category=cat,area=area,image=image,sellerPhone=sellerProfile.phone,sellerAddress=sellerProfile.address);showAdd=false})
}

fun addCart(c:List<CartLine>,p:Product):List<CartLine>{val x=c.toMutableList();val i=x.indexOfFirst{it.product.id==p.id};if(i>=0)x[i]=x[i].copy(qty=x[i].qty+1)else x.add(CartLine(p,1));return x}
fun removeOne(c:List<CartLine>,p:Product):List<CartLine>{val x=c.toMutableList();val i=x.indexOfFirst{it.product.id==p.id};if(i>=0){if(x[i].qty>1)x[i]=x[i].copy(qty=x[i].qty-1)else x.removeAt(i)};return x}

@Composable fun ProductImage(image:String,modifier:Modifier=Modifier){if(image.startsWith("content://")||image.startsWith("file://")){Image(painter=rememberAsyncImagePainter(Uri.parse(image)),contentDescription="Product image",modifier=modifier,contentScale=ContentScale.Crop)}else{Box(modifier=modifier.background(Color(0xFFF2F0FA)),contentAlignment=Alignment.Center){Text(image.ifBlank{"🛍️"},style=MaterialTheme.typography.headlineLarge)}}}

@Composable fun Home(ps:List<Product>,search:String,setSearch:(String)->Unit,seller:()->Unit,add:(Product)->Unit,m:Modifier){LazyColumn(modifier=m.fillMaxSize().background(Color(0xFFF8F8FB)),contentPadding=PaddingValues(bottom=20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
    item{Box(modifier=Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFF6A1B9A),Color(0xFF8E24AA),Color(0xFFFF5C8A),Color(0xFFFFA726)))).padding(horizontal=20.dp,vertical=18.dp)){Column{Row(verticalAlignment=Alignment.CenterVertically){Box(modifier=Modifier.size(58.dp).clip(RoundedCornerShape(18.dp)).background(Color.White.copy(alpha=0.18f)),contentAlignment=Alignment.Center){Box(modifier=Modifier.size(44.dp).clip(RoundedCornerShape(14.dp)).background(Color.White),contentAlignment=Alignment.Center){Text("K",fontWeight=FontWeight.Black,color=Color(0xFF7B2FF7),style=MaterialTheme.typography.headlineMedium)}};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text("KadaiKu Brunei",color=Color.White,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.headlineSmall);Text("Marketplace local kitani 🇧🇳",color=Color.White.copy(alpha=0.9f),style=MaterialTheme.typography.bodyMedium)}};Spacer(Modifier.height(14.dp));Text("Cari barang yang kita mau",color=Color.White,fontWeight=FontWeight.SemiBold,style=MaterialTheme.typography.titleMedium);Spacer(Modifier.height(8.dp));SearchBox(search,setSearch)}}}
    item{Column(Modifier.padding(horizontal=16.dp)){Text("Kategori Popular",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){CategoryCard("🍔","Makanan",Color(0xFFFFE0B2),Modifier.weight(1f));CategoryCard("👕","Fashion",Color(0xFFD1C4E9),Modifier.weight(1f));CategoryCard("💄","Beauty",Color(0xFFFFCDD2),Modifier.weight(1f));CategoryCard("🏠","Rumah",Color(0xFFC8E6C9),Modifier.weight(1f))}}}
    item{Card(modifier=Modifier.padding(horizontal=16.dp).fillMaxWidth(),colors=CardDefaults.cardColors(containerColor=Color(0xFF1E88E5)),shape=RoundedCornerShape(22.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("PROMO HARI ANI 🎉",color=Color.White,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.height(4.dp));Text("Support local seller & discover barang menarik dekat kitani.",color=Color.White)};Text("🇧🇳",style=MaterialTheme.typography.headlineMedium)}}}
    item{Row(Modifier.fillMaxWidth().padding(horizontal=16.dp),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("Barang Berdekatan",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("Pilihan seller sekitar Brunei",style=MaterialTheme.typography.bodySmall,color=Color.Gray)};FilledTonalButton(onClick=seller){Text("+ Jual")}}}
    if(ps.isEmpty())item{Card(modifier=Modifier.padding(horizontal=16.dp).fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("🔎",style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(8.dp));Text("Barang inda jumpa",fontWeight=FontWeight.Bold);Text("Cuba search nama barang, kedai atau kategori lain.",color=Color.Gray)}}}else items(ps){p->ColorfulProductCard(p,add,Modifier.padding(horizontal=16.dp))}
}}

@Composable fun CategoryCard(icon:String,label:String,bg:Color,m:Modifier=Modifier){Card(modifier=m,colors=CardDefaults.cardColors(containerColor=bg),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(vertical=14.dp,horizontal=8.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(icon,style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(4.dp));Text(label,fontWeight=FontWeight.SemiBold,style=MaterialTheme.typography.labelMedium)}}}

@Composable fun ColorfulProductCard(p:Product,add:(Product)->Unit,m:Modifier=Modifier){Card(modifier=m.fillMaxWidth(),shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.padding(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){ProductImage(p.image,Modifier.size(76.dp).clip(RoundedCornerShape(18.dp)));Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium);Text(p.shop,color=Color(0xFF6A1B9A),fontWeight=FontWeight.SemiBold);Text("📍 ${p.area}  •  ${p.category}",style=MaterialTheme.typography.bodySmall,color=Color.Gray);Spacer(Modifier.height(5.dp));Text("B$%.2f".format(p.price),fontWeight=FontWeight.ExtraBold,color=Color(0xFFE65100),style=MaterialTheme.typography.titleMedium)};Button(onClick={add(p)},shape=RoundedCornerShape(14.dp)){Text("Tambah")}};Spacer(Modifier.height(10.dp));HorizontalDivider(color=Color(0xFFEEEEEE));Spacer(Modifier.height(8.dp));Text("Seller Contact",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.labelLarge);Text("📞 ${p.sellerPhone.ifBlank{"Belum diisi"}}",style=MaterialTheme.typography.bodySmall);Text("🏠 ${p.sellerAddress.ifBlank{"Alamat belum diisi"}}",style=MaterialTheme.typography.bodySmall,color=Color.DarkGray)}}}

@Composable fun SearchPage(ps:List<Product>,q:String,setQ:(String)->Unit,add:(Product)->Unit,m:Modifier){Column(m.fillMaxSize().background(Color(0xFFF8F8FB)).padding(16.dp)){Text("Cari barang",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Search ikut barang, kedai atau kategori",style=MaterialTheme.typography.bodyMedium,color=Color.Gray);Spacer(Modifier.height(12.dp));SearchBox(q,setQ);Spacer(Modifier.height(14.dp));if(ps.isEmpty())Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.padding(24.dp).fillMaxWidth(),horizontalAlignment=Alignment.CenterHorizontally){Text("🔍",style=MaterialTheme.typography.headlineLarge);Spacer(Modifier.height(8.dp));Text("Tiada hasil carian",fontWeight=FontWeight.Bold);Text("Cuba keyword lain.",color=Color.Gray)}}else ProductList(ps,add)}}

@Composable fun SearchBox(q:String,setQ:(String)->Unit){Surface(shape=RoundedCornerShape(20.dp),color=Color.White,shadowElevation=3.dp,modifier=Modifier.fillMaxWidth()){OutlinedTextField(value=q,onValueChange=setQ,modifier=Modifier.fillMaxWidth(),singleLine=true,placeholder={Text("Search barang, kedai atau kategori...")},leadingIcon={Text("🔎")},trailingIcon=if(q.isNotBlank()){{TextButton(onClick={setQ("")},contentPadding=PaddingValues(horizontal=8.dp)){Text("✕")}}}else null,shape=RoundedCornerShape(20.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=Color(0xFF7B2FF7),unfocusedBorderColor=Color.Transparent,focusedContainerColor=Color.White,unfocusedContainerColor=Color.White))}}

@Composable fun ProductList(ps:List<Product>,add:(Product)->Unit){LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(ps){p->ColorfulProductCard(p,add)}}}

@Composable fun CartPage(c:List<CartLine>,minus:(Product)->Unit,plus:(Product)->Unit,checkout:(String,Double)->Unit,m:Modifier){var delivery by remember{mutableStateOf("Delivery")};val subtotal=c.sumOf{it.product.price*it.qty};val fee=if(c.isEmpty())0.0 else if(delivery=="Pickup")0.0 else 3.0;Column(m.padding(16.dp)){Text("Troli",style=MaterialTheme.typography.headlineSmall);Spacer(Modifier.height(12.dp));if(c.isEmpty())Text("Troli masih kosong")else{LazyColumn(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(8.dp)){items(c){x->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){ProductImage(x.product.image,Modifier.size(48.dp).clip(RoundedCornerShape(12.dp)));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(x.product.name,fontWeight=FontWeight.Bold);money(x.product.price)};TextButton(onClick={minus(x.product)}){Text("−")};Text(x.qty.toString());TextButton(onClick={plus(x.product)}){Text("+")}}}}};Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(selected=delivery=="Delivery",onClick={delivery="Delivery"},label={Text("Delivery B$3")});FilterChip(selected=delivery=="Pickup",onClick={delivery="Pickup"},label={Text("Pickup")})};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Jumlah",fontWeight=FontWeight.Bold);money(subtotal+fee)};Button(onClick={if(c.isNotEmpty())checkout(delivery,subtotal+fee)},modifier=Modifier.fillMaxWidth()){Text("Place Order")}}}}

@Composable fun ProfilePage(orders:List<Order>,seller:()->Unit,m:Modifier){LazyColumn(modifier=m.fillMaxSize().background(Color(0xFFF8F8FB)),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Akaun",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};item{Button(onClick=seller,modifier=Modifier.fillMaxWidth()){Text("🏪 Seller Mode")}};item{Text("Pesanan Saya",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};if(orders.isEmpty())item{Text("Belum ada pesanan")}else items(orders.reversed()){order->LiveOrderCard(order)}}}

@Composable fun LiveOrderCard(order:Order){var stage by remember(order.id){mutableIntStateOf(0)};var showTracking by remember(order.id){mutableStateOf(false)};val deliveryStages=listOf("Order diterima","Sedang disediakan","Rider mengambil","Dalam perjalanan","Sampai");val pickupStages=listOf("Order diterima","Sedang disediakan","Sedia untuk pickup","Selesai");val stages=if(order.delivery=="Pickup")pickupStages else deliveryStages;LaunchedEffect(order.id){while(stage<stages.lastIndex){delay(7000);stage++}};val eta=when{order.delivery=="Pickup"&&stage<2->"± 10 min";order.delivery=="Pickup"->"Boleh ambil sekarang";stage==0->"± 25 min";stage==1->"± 20 min";stage==2->"± 15 min";stage==3->"± 7 min";else->"Sudah sampai"};val statusColor=when(stage){0->Color(0xFF6A1B9A);1->Color(0xFFF57C00);2->Color(0xFF00897B);3->Color(0xFF1E88E5);else->Color(0xFF2E7D32)};Card(shape=RoundedCornerShape(22.dp),colors=CardDefaults.cardColors(containerColor=Color.White),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("Order #${order.id}",fontWeight=FontWeight.Bold);Text("${order.delivery} • ${order.lines.sumOf{it.qty}} item",color=Color.Gray)};Text("LIVE",color=Color.White,fontWeight=FontWeight.Bold,modifier=Modifier.clip(RoundedCornerShape(50)).background(Color(0xFFE53935)).padding(horizontal=10.dp,vertical=4.dp))};Spacer(Modifier.height(12.dp));Text(stages[stage],fontWeight=FontWeight.ExtraBold,color=statusColor,style=MaterialTheme.typography.titleMedium);Text("Anggaran: $eta");Spacer(Modifier.height(10.dp));LinearProgressIndicator(progress={(stage+1).toFloat()/stages.size.toFloat()},modifier=Modifier.fillMaxWidth().height(8.dp).clip(RoundedCornerShape(50)));Spacer(Modifier.height(10.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Rider: Ahmad");Text("B$%.2f".format(order.total),fontWeight=FontWeight.Bold)};order.lines.firstOrNull()?.product?.let{p->Spacer(Modifier.height(8.dp));Text("Seller: ${p.shop}",fontWeight=FontWeight.Bold);Text("📞 ${p.sellerPhone}");Text("🏠 ${p.sellerAddress}")};Spacer(Modifier.height(8.dp));OutlinedButton(onClick={showTracking=!showTracking},modifier=Modifier.fillMaxWidth()){Text(if(showTracking)"Tutup Tracking" else "📍 Live Tracking")};if(showTracking){Spacer(Modifier.height(8.dp));Card(colors=CardDefaults.cardColors(containerColor=Color(0xFFE3F2FD)),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(12.dp)){Text("Live rider location",fontWeight=FontWeight.Bold);Text("🛵 Rider sedang bergerak menuju lokasi buyer.");Text("Demo GPS tracking untuk testing version.",style=MaterialTheme.typography.bodySmall,color=Color.Gray)}}}}}}

fun startOfWeek(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_WEEK,firstDayOfWeek);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}
fun startOfMonth(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_MONTH,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}
fun startOfYear(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_YEAR,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun SellerSheet(onClose:()->Unit,onAdd:()->Unit,products:List<Product>,orders:List<Order>,profile:SellerProfile,onProfileChange:(SellerProfile)->Unit,onDelete:(String)->Unit){var shop by remember(profile){mutableStateOf(profile.shop)};var phone by remember(profile){mutableStateOf(profile.phone)};var address by remember(profile){mutableStateOf(profile.address)};val now=System.currentTimeMillis();val weekOrders=orders.filter{it.createdAt>=startOfWeek(now)};val monthOrders=orders.filter{it.createdAt>=startOfMonth(now)};val yearOrders=orders.filter{it.createdAt>=startOfYear(now)};ModalBottomSheet(onDismissRequest=onClose){LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Seller Dashboard",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};item{Card(colors=CardDefaults.cardColors(containerColor=Color(0xFFF3E5F5)),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(14.dp)){Text("Seller Contact",fontWeight=FontWeight.Bold);OutlinedTextField(shop,{shop=it},label={Text("Nama kedai")},modifier=Modifier.fillMaxWidth());OutlinedTextField(phone,{phone=it},label={Text("No. telefon")},modifier=Modifier.fillMaxWidth());OutlinedTextField(address,{address=it},label={Text("Alamat kedai")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(8.dp));Button(onClick={onProfileChange(SellerProfile(shop,phone,address))},modifier=Modifier.fillMaxWidth(),enabled=phone.isNotBlank()&&address.isNotBlank()){Text("Simpan Contact")}}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){StatCard("Minggu",weekOrders.size,weekOrders.sumOf{it.total},Modifier.weight(1f));StatCard("Bulan",monthOrders.size,monthOrders.sumOf{it.total},Modifier.weight(1f));StatCard("Tahun",yearOrders.size,yearOrders.sumOf{it.total},Modifier.weight(1f))}};item{Button(onClick=onAdd,modifier=Modifier.fillMaxWidth(),enabled=profile.phone.isNotBlank()&&profile.address.isNotBlank()){Text("+ Tambah Produk")}};item{Text("Produk saya",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};val mine=products.filter{it.shop==profile.shop};if(mine.isEmpty())item{Text("Belum ada produk")};else items(mine){p->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){ProductImage(p.image,Modifier.size(54.dp).clip(RoundedCornerShape(12.dp)));Spacer(Modifier.width(10.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold);money(p.price)};TextButton(onClick={onDelete(p.id)}){Text("Padam")}}}};item{Text("Recent Orders",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold)};if(orders.isEmpty())item{Text("Belum ada order")};else items(orders.takeLast(5).reversed()){o->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("#${o.id}",fontWeight=FontWeight.Bold);Text("${o.delivery} • ${o.lines.sumOf{it.qty}} item");money(o.total)}}}};item{Spacer(Modifier.height(30.dp))}}}}

@Composable fun StatCard(label:String,count:Int,sales:Double,m:Modifier=Modifier){Card(modifier=m,shape=RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=Color.White)){Column(Modifier.padding(12.dp)){Text(label,fontWeight=FontWeight.Bold);Text("$count order",style=MaterialTheme.typography.bodySmall,color=Color.Gray);Text("B$%.2f".format(sales),fontWeight=FontWeight.ExtraBold,color=Color(0xFF6A1B9A))}}}

@Composable fun AddProductDialog(sellerProfile:SellerProfile,onDismiss:()->Unit,onSave:(String,Double,String,String,String)->Unit){var n by remember{mutableStateOf("")};var pr by remember{mutableStateOf("")};var cat by remember{mutableStateOf("Makanan")};var area by remember{mutableStateOf("")};var imageUri by remember{mutableStateOf("")};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri:Uri?->imageUri=uri?.toString().orEmpty()};AlertDialog(onDismissRequest=onDismiss,title={Text("Tambah Produk")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Gambar produk wajib",fontWeight=FontWeight.Bold);if(imageUri.isNotBlank())ProductImage(imageUri,Modifier.fillMaxWidth().height(160.dp).clip(RoundedCornerShape(16.dp)))else Card(colors=CardDefaults.cardColors(containerColor=Color(0xFFF3F0FA)),shape=RoundedCornerShape(16.dp),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(22.dp).fillMaxWidth(),horizontalAlignment=Alignment.CenterHorizontally){Text("🖼️",style=MaterialTheme.typography.headlineLarge);Text("Belum pilih gambar")}};OutlinedButton(onClick={launcher.launch("image/*")},modifier=Modifier.fillMaxWidth()){Text(if(imageUri.isBlank())"Pilih gambar dari Gallery" else "Tukar gambar")};OutlinedTextField(n,{n=it},label={Text("Nama produk")},modifier=Modifier.fillMaxWidth());OutlinedTextField(pr,{pr=it},label={Text("Harga B$")},modifier=Modifier.fillMaxWidth());OutlinedTextField(cat,{cat=it},label={Text("Kategori")},modifier=Modifier.fillMaxWidth());OutlinedTextField(area,{area=it},label={Text("Kawasan")},modifier=Modifier.fillMaxWidth());Text("Seller: ${sellerProfile.shop}",style=MaterialTheme.typography.bodySmall);Text("📞 ${sellerProfile.phone}",style=MaterialTheme.typography.bodySmall);Text("🏠 ${sellerProfile.address}",style=MaterialTheme.typography.bodySmall)}},confirmButton={Button(enabled=n.isNotBlank()&&pr.toDoubleOrNull()!=null&&area.isNotBlank()&&imageUri.isNotBlank(),onClick={onSave(n,pr.toDouble(),cat,area,imageUri)}){Text("Simpan")}},dismissButton={TextButton(onClick=onDismiss){Text("Batal")}})}