package com.kadaiku.brunei

import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.dp
import coil.compose.rememberAsyncImagePainter
import kotlinx.coroutines.delay
import java.util.Calendar
import java.util.UUID
import kotlin.math.roundToInt

data class UserAccount(val id:String=UUID.randomUUID().toString(),val username:String,val password:String,val role:String,val shop:String="",val phone:String="",val address:String="")
data class SellerProfile(val shop:String,val phone:String,val address:String)
data class Product(val id:String=UUID.randomUUID().toString(),val name:String,val price:Double,val shop:String,val category:String,val area:String,val image:String,val sellerPhone:String,val sellerAddress:String,val sellerId:String="sample",val stock:Int=10)
data class CartLine(val product:Product,var qty:Int)
data class AppNotice(val id:String=UUID.randomUUID().toString(),val target:String,val title:String,val message:String,val createdAt:Long=System.currentTimeMillis())
data class Order(val id:String=UUID.randomUUID().toString().take(8).uppercase(),val buyerId:String="",val lines:List<CartLine>,val delivery:String,val district:String="",val deliveryAddress:String="",val deliveryLocation:String="",val deliveryFee:Double=0.0,val paymentMethod:String="Cash",val total:Double,val runnerName:String="",val runnerPhone:String="",val createdAt:Long=System.currentTimeMillis(),val deliveredAt:Long?=null)

fun tr(lang:String,ms:String,en:String)=if(lang=="English")en else ms
@Composable fun money(v:Double)=Text("B$%.2f".format(v))
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{KadaiKuApp()}}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun KadaiKuApp(){
    var language by remember{mutableStateOf("Melayu")}
    var accounts by remember{mutableStateOf(listOf<UserAccount>())}
    var currentUser by remember{mutableStateOf<UserAccount?>(null)}
    var rememberedUsername by remember{mutableStateOf("")}
    var rememberedPassword by remember{mutableStateOf("")}
    var rememberLogin by remember{mutableStateOf(false)}
    var showRegister by remember{mutableStateOf(false)}
    var tab by remember{mutableIntStateOf(0)}
    var products by remember{mutableStateOf(listOf(
        Product(name="Kek Coklat Premium",price=15.0,shop="Dapur Aisyah",category="Makanan",area="Gadong",image="🍰",sellerPhone="+673 7XX XXXX",sellerAddress="Gadong, Brunei-Muara",sellerId="sample-aisyah",stock=12),
        Product(name="Perfume Oud",price=20.0,shop="Brunei Fragrance",category="Beauty",area="Kiulap",image="🧴",sellerPhone="+673 8XX XXXX",sellerAddress="Kiulap, Brunei-Muara",sellerId="sample-fragrance",stock=8),
        Product(name="Baju Melayu",price=35.0,shop="Kedai Kita",category="Fashion",area="Bandar",image="👕",sellerPhone="+673 7XX XXXX",sellerAddress="Bandar Seri Begawan",sellerId="sample-kita",stock=10),
        Product(name="Frozen Food Combo",price=12.0,shop="Mama's Frozen",category="Makanan",area="Tutong",image="🥟",sellerPhone="+673 8XX XXXX",sellerAddress="Tutong, Brunei",sellerId="sample-mama",stock=15)
    ))}
    var cart by remember{mutableStateOf(listOf<CartLine>())};var orders by remember{mutableStateOf(listOf<Order>())};var notices by remember{mutableStateOf(listOf<AppNotice>())};var search by remember{mutableStateOf("")};var showSeller by remember{mutableStateOf(false)};var showAdd by remember{mutableStateOf(false)};var selectedProduct by remember{mutableStateOf<Product?>(null)};var selectedSellerId by remember{mutableStateOf<String?>(null)};var historyOrder by remember{mutableStateOf<Order?>(null)};var showSupport by remember{mutableStateOf(false)};var supportX by remember{mutableStateOf(0f)};var supportY by remember{mutableStateOf(0f)}

    if(currentUser==null){if(showRegister){RegisterScreen(language,{language=it},onBack={showRegister=false},onRegister={username,password,role,shop,phone,address->if(accounts.none{it.username.equals(username,true)}){val account=UserAccount(username=username.trim(),password=password,role=role,shop=shop.trim(),phone=phone.trim(),address=address.trim());accounts=accounts+account;currentUser=account;showRegister=false}})}else{LoginScreen(language,{language=it},if(rememberLogin)rememberedUsername else "",if(rememberLogin)rememberedPassword else "",rememberLogin,onLogin={username,password,rememberMe->accounts.firstOrNull{it.username.equals(username.trim(),true)&&it.password==password}?.let{currentUser=it;rememberLogin=rememberMe;if(rememberMe){rememberedUsername=username.trim();rememberedPassword=password}else{rememberedUsername="";rememberedPassword=""}}},onRegister={showRegister=true})};return}

    val user=currentUser!!;val sellerProfile=SellerProfile(user.shop.ifBlank{tr(language,"Kedai Saya","My Shop")},user.phone,user.address);val availableProducts=products.filter{it.stock>0};val filtered=availableProducts.filter{search.isBlank()||it.name.contains(search,true)||it.shop.contains(search,true)||it.category.contains(search,true)};val buyerOrders=orders.filter{it.buyerId==user.id};val sellerNotices=notices.filter{it.target==user.id}
    Box(Modifier.fillMaxSize()){
        Scaffold(containerColor=Color.White,topBar={CenterAlignedTopAppBar(title={Text("KadaiKu 🇧🇳",fontWeight=FontWeight.Bold,color=Color(0xFF0D47A1))})},bottomBar={NavigationBar{listOf(tr(language,"Home","Home"),tr(language,"Cari","Search"),tr(language,"Troli (${cart.sumOf{it.qty}})","Cart (${cart.sumOf{it.qty}})"),tr(language,"Profil","Profile")).forEachIndexed{i,l->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={},label={Text(l)})}}}){pad->
            when(tab){
                0->Home(filtered,search,{search=it},{if(user.role=="Seller")showSeller=true},{p->cart=addCart(cart,p)},{selectedProduct=it},{selectedSellerId=it.sellerId},Modifier.padding(pad),user.role=="Seller",language)
                1->SearchPage(filtered,search,{search=it},{p->cart=addCart(cart,p)},{selectedProduct=it},{selectedSellerId=it.sellerId},Modifier.padding(pad),language)
                2->CartPage(cart,{p->cart=removeOne(cart,p)},{p->cart=addCart(cart,p)},{p->cart=removeItem(cart,p)},checkout={delivery,district,address,location,fee,payment,total->if(cart.isNotEmpty()){val stockOk=cart.all{line->products.firstOrNull{it.id==line.product.id}?.stock?.let{it>=line.qty}==true};if(stockOk){val runner=if(delivery=="Pickup")Pair("","")else assignMarketplaceRunner();val order=Order(buyerId=user.id,lines=cart.map{it.copy()},delivery=delivery,district=district,deliveryAddress=address,deliveryLocation=location,deliveryFee=fee,paymentMethod=payment,total=total,runnerName=runner.first,runnerPhone=runner.second);orders=orders+order;products=products.map{p->val bought=cart.firstOrNull{it.product.id==p.id}?.qty?:0;if(bought>0)p.copy(stock=(p.stock-bought).coerceAtLeast(0))else p};order.lines.groupBy{it.product.sellerId}.forEach{(sellerId,lines)->if(!sellerId.startsWith("sample-"))notices=notices+AppNotice(target=sellerId,title="New order #${order.id}",message=tr(language,"Buyer membeli ${lines.sumOf{it.qty}} item. Sediakan barang untuk pickup runner.","Buyer purchased ${lines.sumOf{it.qty}} item(s). Prepare them for runner pickup."))};if(order.delivery!="Pickup"){val pickupText=order.lines.distinctBy{it.product.sellerId}.joinToString(" • "){"${it.product.shop}: ${it.product.sellerAddress}"};val dest=listOf(order.deliveryAddress,order.deliveryLocation).filter{it.isNotBlank()}.joinToString(" | ");notices=notices+AppNotice(target="runner:${order.runnerName}",title="Pickup job #${order.id}",message="Pickup: $pickupText | Deliver: $dest")};cart=listOf();tab=3}}},m=Modifier.padding(pad),language=language)
                else->ProfilePage(buyerOrders,user,sellerNotices,{if(user.role=="Seller")showSeller=true},{currentUser=null;cart=listOf();tab=0},{orderId->val target=orders.firstOrNull{it.id==orderId};orders=orders.map{o->if(o.id==orderId&&o.deliveredAt==null)o.copy(deliveredAt=System.currentTimeMillis())else o};target?.lines?.map{it.product.sellerId}?.distinct()?.filterNot{it.startsWith("sample-")}?.forEach{sellerId->notices=notices+AppNotice(target=sellerId,title="Order #$orderId completed",message=tr(language,"Order sudah complete dan sudah masuk History Seller.","Order is complete and has been moved to Seller History."))}},{historyOrder=it},Modifier.padding(pad),language,{language=it})
            }
        }
        FloatingActionButton(onClick={showSupport=true},containerColor=Color(0xFF20C56B),contentColor=Color.White,shape=CircleShape,modifier=Modifier.align(Alignment.BottomEnd).padding(16.dp).offset{IntOffset(supportX.roundToInt(),supportY.roundToInt())}.pointerInput(Unit){detectDragGestures{change,dragAmount->change.consume();supportX+=dragAmount.x;supportY+=dragAmount.y}}){Text("💬")}
    }
    selectedProduct?.let{p->ProductDetailSheet(p,{selectedProduct=null},{cart=addCart(cart,p)},{selectedProduct=null;selectedSellerId=p.sellerId},language)}
    selectedSellerId?.let{id->products.firstOrNull{it.sellerId==id}?.let{anchor->SellerStoreSheet(id,products,anchor,{selectedSellerId=null},{cart=addCart(cart,it)},{selectedProduct=it;selectedSellerId=null},language)}}
    historyOrder?.let{o->HistoryDetailSheet(o,{historyOrder=null},language)}
    if(showSupport)CustomerServiceSheet({showSupport=false},language)
    if(showSeller&&user.role=="Seller")SellerSheet({showSeller=false},{showAdd=true},products,orders,sellerProfile,user.id,{id->products=products.filterNot{it.id==id}},language)
    if(showAdd&&user.role=="Seller")AddProductDialog(sellerProfile,{showAdd=false},{name,price,cat,image,stock->products=products+Product(name=name,price=price,shop=sellerProfile.shop.ifBlank{tr(language,"Kedai Saya","My Shop")},category=cat,area=sellerProfile.address,image=image,sellerPhone=sellerProfile.phone,sellerAddress=sellerProfile.address,sellerId=user.id,stock=stock);showAdd=false},language)
}

@Composable fun LanguageChooser(language:String,onLanguage:(String)->Unit){Column{Text(if(language=="English")"Language" else "Bahasa",fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(selected=language=="Melayu",onClick={onLanguage("Melayu")},label={Text("Melayu")});FilterChip(selected=language=="English",onClick={onLanguage("English")},label={Text("English")})}}}
@Composable fun LoginScreen(language:String,onLanguage:(String)->Unit,initialUsername:String,initialPassword:String,initialRemember:Boolean,onLogin:(String,String,Boolean)->Unit,onRegister:()->Unit){var u by remember{mutableStateOf(initialUsername)};var p by remember{mutableStateOf(initialPassword)};var showPassword by remember{mutableStateOf(false)};var rememberMe by remember{mutableStateOf(initialRemember)};Column(Modifier.fillMaxSize().background(Color.White).padding(24.dp),verticalArrangement=Arrangement.Center){Text("KadaiKu Brunei",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold,color=Color(0xFF0D47A1));LanguageChooser(language,onLanguage);Spacer(Modifier.height(10.dp));Text(tr(language,"Login ke akaun kita","Login to your account"),color=Color.Gray);OutlinedTextField(u,{u=it},label={Text("Username")},modifier=Modifier.fillMaxWidth());OutlinedTextField(p,{p=it},label={Text("Password")},modifier=Modifier.fillMaxWidth(),visualTransformation=if(showPassword)VisualTransformation.None else PasswordVisualTransformation(),trailingIcon={TextButton(onClick={showPassword=!showPassword}){Text(if(showPassword)tr(language,"Sembunyi","Hide") else tr(language,"Tunjuk","Show"))}});Row(verticalAlignment=Alignment.CenterVertically){Checkbox(rememberMe,{rememberMe=it});Text(tr(language,"Ingat saya","Remember me"))};Button(onClick={onLogin(u,p,rememberMe)},modifier=Modifier.fillMaxWidth(),enabled=u.isNotBlank()&&p.isNotBlank()){Text("Login")};TextButton(onClick=onRegister,modifier=Modifier.fillMaxWidth()){Text(tr(language,"Pengguna baru? Daftar","New user? Register"))}}}
@Composable fun RegisterScreen(language:String,onLanguage:(String)->Unit,onBack:()->Unit,onRegister:(String,String,String,String,String,String)->Unit){var u by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var showPassword by remember{mutableStateOf(false)};var role by remember{mutableStateOf("Buyer")};var shop by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var sellerLocation by remember{mutableStateOf("")};LazyColumn(Modifier.fillMaxSize().background(Color.White),contentPadding=PaddingValues(24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{LanguageChooser(language,onLanguage)};item{Text(tr(language,"Buat Akaun","Create Account"),style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.ExtraBold)};item{OutlinedTextField(u,{u=it},label={Text("Username")},modifier=Modifier.fillMaxWidth())};item{OutlinedTextField(p,{p=it},label={Text("Password")},modifier=Modifier.fillMaxWidth(),visualTransformation=if(showPassword)VisualTransformation.None else PasswordVisualTransformation(),trailingIcon={TextButton(onClick={showPassword=!showPassword}){Text(if(showPassword)tr(language,"Sembunyi","Hide")else tr(language,"Tunjuk","Show"))}})};item{Text(tr(language,"Jenis akaun","Account type"),fontWeight=FontWeight.Bold);Row{FilterChip(role=="Buyer",{role="Buyer"},{Text("Buyer")});Spacer(Modifier.width(8.dp));FilterChip(role=="Seller",{role="Seller"},{Text("Seller")})}};if(role=="Seller"){item{OutlinedTextField(shop,{shop=it},label={Text(tr(language,"Nama kedai","Shop name"))},modifier=Modifier.fillMaxWidth())};item{OutlinedTextField(phone,{phone=it},label={Text(tr(language,"No. telefon seller","Seller phone number"))},modifier=Modifier.fillMaxWidth())};item{OutlinedTextField(sellerLocation,{sellerLocation=it},label={Text(tr(language,"Lokasi Seller","Seller Location"))},placeholder={Text(tr(language,"Paste link Google Maps atau coordinates","Paste Google Maps link or coordinates"))},modifier=Modifier.fillMaxWidth())}};item{Button(onClick={onRegister(u,p,role,shop,phone,sellerLocation)},modifier=Modifier.fillMaxWidth(),enabled=u.isNotBlank()&&p.length>=4&&(role=="Buyer"||(shop.isNotBlank()&&phone.isNotBlank()&&sellerLocation.isNotBlank()))){Text(tr(language,"Buat Akaun","Create Account"))}};item{TextButton(onClick=onBack,modifier=Modifier.fillMaxWidth()){Text(tr(language,"Kembali ke Login","Back to Login"))}}}}

fun assignMarketplaceRunner():Pair<String,String>{val runners=listOf(Pair("Hakim","+673 7XX 1010"),Pair("Faris","+673 8XX 2020"),Pair("Azim","+673 7XX 3030"),Pair("Rizal","+673 8XX 4040"));return runners.random()}
fun deliveryFeeFor(district:String):Double=when(district){"Brunei-Muara"->3.0;"Tutong"->5.0;"Kuala Belait"->6.0;"Temburong"->8.0;else->3.0}
fun addCart(c:List<CartLine>,p:Product):List<CartLine>{if(p.stock<=0)return c;val x=c.toMutableList();val i=x.indexOfFirst{it.product.id==p.id};if(i>=0){if(x[i].qty<p.stock)x[i]=x[i].copy(qty=x[i].qty+1)}else x.add(CartLine(p,1));return x}
fun removeOne(c:List<CartLine>,p:Product):List<CartLine>{val x=c.toMutableList();val i=x.indexOfFirst{it.product.id==p.id};if(i>=0){if(x[i].qty>1)x[i]=x[i].copy(qty=x[i].qty-1)else x.removeAt(i)};return x}
fun removeItem(c:List<CartLine>,p:Product)=c.filterNot{it.product.id==p.id}
fun sellerOrderValue(order:Order,sellerId:String)=order.lines.filter{it.product.sellerId==sellerId}.sumOf{it.product.price*it.qty}
@Composable fun ProductImage(image:String,modifier:Modifier=Modifier){if(image.startsWith("content://")||image.startsWith("file://")){Image(rememberAsyncImagePainter(Uri.parse(image)),"Product image",modifier,contentScale=ContentScale.Crop)}else Box(modifier.background(Color(0xFFF5F9FF)),contentAlignment=Alignment.Center){Text(image.ifBlank{"🛍️"},style=MaterialTheme.typography.headlineLarge)}}

@Composable fun Home(ps:List<Product>,search:String,setSearch:(String)->Unit,seller:()->Unit,add:(Product)->Unit,view:(Product)->Unit,openSeller:(Product)->Unit,m:Modifier,isSeller:Boolean,language:String){LazyColumn(m.fillMaxSize().background(Color.White),contentPadding=PaddingValues(bottom=20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Box(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFF0D47A1),Color(0xFF1976D2),Color(0xFF42A5F5)))).padding(20.dp)){Column{Text("KadaiKu Brunei",color=Color.White,fontWeight=FontWeight.ExtraBold,style=MaterialTheme.typography.headlineSmall);Text(tr(language,"Marketplace local kitani 🇧🇳","Your local marketplace 🇧🇳"),color=Color.White);Spacer(Modifier.height(12.dp));SearchBox(search,setSearch,language)}}};item{Text(tr(language,"Kategori Popular","Popular Categories"),modifier=Modifier.padding(horizontal=16.dp),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};item{Row(Modifier.padding(horizontal=16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){CategoryCard("🍔",tr(language,"Makanan","Food"),Modifier.weight(1f));CategoryCard("👕",tr(language,"Fashion","Fashion"),Modifier.weight(1f));CategoryCard("💄",tr(language,"Beauty","Beauty"),Modifier.weight(1f))}};item{Row(Modifier.fillMaxWidth().padding(horizontal=16.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(tr(language,"Barang Berdekatan","Nearby Products"),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);if(isSeller)FilledTonalButton(onClick=seller){Text(tr(language,"Dashboard","Dashboard"))}}};if(ps.isEmpty())item{Text(tr(language,"Barang inda jumpa","No products found"),modifier=Modifier.padding(16.dp))};items(ps){p->ColorfulProductCard(p,add,view,openSeller,Modifier.padding(horizontal=16.dp),language)}}}
@Composable fun CategoryCard(icon:String,label:String,m:Modifier=Modifier){Card(modifier=m){Column(Modifier.padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(icon);Text(label,fontWeight=FontWeight.SemiBold)}}}
@Composable fun ColorfulProductCard(p:Product,add:(Product)->Unit,view:(Product)->Unit,openSeller:(Product)->Unit,m:Modifier=Modifier,language:String){Card(modifier=m.fillMaxWidth()){Column(Modifier.padding(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){ProductImage(p.image,Modifier.size(76.dp).clip(RoundedCornerShape(18.dp)));Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold);Text(p.shop,color=Color(0xFF1565C0),modifier=Modifier.clickable{openSeller(p)});Text(tr(language,"Lihat kedai seller","View seller store"),style=MaterialTheme.typography.bodySmall,color=Color(0xFF1565C0),modifier=Modifier.clickable{openSeller(p)});Text("${tr(language,"Stok","Stock")}: ${p.stock}",style=MaterialTheme.typography.bodySmall);Text("B$%.2f".format(p.price),fontWeight=FontWeight.ExtraBold)}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({view(p)},Modifier.weight(1f)){Text(tr(language,"Lihat Produk","View Product"))};Button({add(p)},Modifier.weight(1f),enabled=p.stock>0){Text(tr(language,"Tambah","Add"))}}}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun ProductDetailSheet(product:Product,onClose:()->Unit,onAdd:()->Unit,onSeller:()->Unit,language:String){ModalBottomSheet(onDismissRequest=onClose){Column(Modifier.padding(20.dp)){ProductImage(product.image,Modifier.fillMaxWidth().height(240.dp));Text(product.name,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("B$%.2f".format(product.price));Text("${tr(language,"Stok","Stock")}: ${product.stock}");Card(Modifier.fillMaxWidth().clickable{onSeller()}){Column(Modifier.padding(14.dp)){Text(tr(language,"Profil Seller","Seller Profile"),fontWeight=FontWeight.Bold);Text("🏪 ${product.shop}");Text("📞 ${product.sellerPhone}");Text("📍 ${product.sellerAddress}")}};Button(onClick=onAdd,modifier=Modifier.fillMaxWidth()){Text(tr(language,"Tambah ke Troli","Add to Cart"))}}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun SellerStoreSheet(sellerId:String,products:List<Product>,anchor:Product,onClose:()->Unit,onAdd:(Product)->Unit,onView:(Product)->Unit,language:String){val sellerProducts=products.filter{it.sellerId==sellerId&&it.stock>0};ModalBottomSheet(onDismissRequest=onClose){LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("🏪 ${anchor.shop}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("📞 ${anchor.sellerPhone}");Text("📍 ${anchor.sellerAddress}")};item{Text(tr(language,"Semua barang seller","All seller products"),fontWeight=FontWeight.Bold)};if(sellerProducts.isEmpty())item{Text(tr(language,"Semua barang sudah habis","All products are sold out"))};items(sellerProducts){p->ColorfulProductCard(p,onAdd,onView,{},language=language)}}}}
@Composable fun SearchPage(ps:List<Product>,q:String,setQ:(String)->Unit,add:(Product)->Unit,view:(Product)->Unit,openSeller:(Product)->Unit,m:Modifier,language:String){Column(m.fillMaxSize().padding(16.dp)){Text(tr(language,"Cari barang","Search products"),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);SearchBox(q,setQ,language);Spacer(Modifier.height(12.dp));ProductList(ps,add,view,openSeller,language)}}
@Composable fun SearchBox(q:String,setQ:(String)->Unit,language:String){OutlinedTextField(q,setQ,Modifier.fillMaxWidth(),singleLine=true,placeholder={Text(tr(language,"Cari barang, kedai atau kategori...","Search products, shops or categories..."))})}
@Composable fun ProductList(ps:List<Product>,add:(Product)->Unit,view:(Product)->Unit,openSeller:(Product)->Unit,language:String){LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)){items(ps){p->ColorfulProductCard(p,add,view,openSeller,language=language)}}}

@Composable fun CartPage(c:List<CartLine>,minus:(Product)->Unit,plus:(Product)->Unit,remove:(Product)->Unit,checkout:(String,String,String,String,Double,String,Double)->Unit,m:Modifier,language:String){var delivery by remember{mutableStateOf("Delivery")};var district by remember{mutableStateOf("Brunei-Muara")};var address by remember{mutableStateOf("")};var location by remember{mutableStateOf("")};var payment by remember{mutableStateOf("Cash")};val subtotal=c.sumOf{it.product.price*it.qty};val fee=if(c.isEmpty()||delivery=="Pickup")0.0 else deliveryFeeFor(district);Column(m.padding(16.dp)){Text(tr(language,"Troli","Cart"),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(c.isEmpty())Text(tr(language,"Troli masih kosong","Cart is empty"))else{LazyColumn(Modifier.weight(1f)){items(c){x->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(10.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.product.name,fontWeight=FontWeight.Bold);Text("${tr(language,"Kuantiti","Qty")}: ${x.qty}")};TextButton({remove(x.product)}){Text(tr(language,"Buang","Remove"))};TextButton({minus(x.product)}){Text("−")};TextButton({plus(x.product)},enabled=x.qty<x.product.stock){Text("+")}}}}};Row{FilterChip(delivery=="Delivery",{delivery="Delivery"},{Text("Delivery")});Spacer(Modifier.width(8.dp));FilterChip(delivery=="Pickup",{delivery="Pickup"},{Text("Pickup")})};if(delivery=="Delivery"){Text(tr(language,"Pilih daerah delivery","Choose delivery district"),fontWeight=FontWeight.Bold);listOf("Brunei-Muara","Tutong","Kuala Belait","Temburong").forEach{d->FilterChip(district==d,{district=d},{Text(d)})};OutlinedTextField(address,{address=it},label={Text(tr(language,"Alamat delivery buyer","Buyer delivery address"))},modifier=Modifier.fillMaxWidth());OutlinedTextField(location,{location=it},label={Text(tr(language,"Share location / Maps link / coordinates","Share location / Maps link / coordinates"))},modifier=Modifier.fillMaxWidth())};Text(tr(language,"Pembayaran","Payment"),fontWeight=FontWeight.Bold);Row{FilterChip(payment=="Cash",{payment="Cash"},{Text("Cash")});Spacer(Modifier.width(8.dp));FilterChip(payment=="Transfer",{payment="Transfer"},{Text("Transfer")})};Text("${tr(language,"Jumlah","Total")}: B$%.2f".format(subtotal+fee),fontWeight=FontWeight.Bold);Button(onClick={checkout(delivery,if(delivery=="Pickup")"Pickup"else district,if(delivery=="Pickup")""else address,if(delivery=="Pickup")""else location,fee,payment,subtotal+fee)},modifier=Modifier.fillMaxWidth(),enabled=delivery=="Pickup"||address.isNotBlank()||location.isNotBlank()){Text(tr(language,"Buat Pesanan","Place Order"))}}}}

@Composable fun ProfilePage(orders:List<Order>,user:UserAccount,notices:List<AppNotice>,seller:()->Unit,logout:()->Unit,markDelivered:(String)->Unit,openHistory:(Order)->Unit,m:Modifier,language:String,onLanguage:(String)->Unit){val active=orders.filter{it.deliveredAt==null};val history=orders.filter{it.deliveredAt!=null};LazyColumn(m.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text(tr(language,"Akaun","Account"),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("👤 ${user.username}");LanguageChooser(language,onLanguage)};if(user.role=="Seller")item{Button(seller,Modifier.fillMaxWidth()){Text(tr(language,"🏪 Seller Dashboard","🏪 Seller Dashboard"))}};if(user.role=="Seller")items(notices.reversed()){n->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp)){Text(n.title,fontWeight=FontWeight.Bold);Text(n.message)}}};item{OutlinedButton(logout,Modifier.fillMaxWidth()){Text("Logout")}};item{Text(tr(language,"Pesanan Aktif","Active Orders"),fontWeight=FontWeight.Bold)};items(active.reversed()){o->LiveOrderCard(o,{markDelivered(o.id)},language)};item{Text(tr(language,"History Delivery","Delivery History"),fontWeight=FontWeight.Bold)};items(history.reversed()){o->Box(Modifier.clickable{openHistory(o)}){DeliveredOrderCard(o,language)}}}}
@Composable fun LiveOrderCard(order:Order,onDelivered:()->Unit,language:String){var stage by remember(order.id){mutableIntStateOf(0)};val stages=if(order.delivery=="Pickup")listOf(tr(language,"Order diterima","Order received"),tr(language,"Sedang disediakan","Preparing"),tr(language,"Sedia untuk pickup","Ready for pickup"),tr(language,"Selesai","Complete"))else listOf(tr(language,"Order diterima","Order received"),tr(language,"Seller menyiapkan barang","Seller preparing items"),tr(language,"Runner collect semua seller","Runner collecting from sellers"),tr(language,"Dalam perjalanan","On the way"),tr(language,"Sampai","Delivered"));LaunchedEffect(order.id){while(stage<stages.lastIndex){delay(7000);stage++};if(order.deliveredAt==null)onDelivered()};Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("#${order.id}",fontWeight=FontWeight.Bold);Text(stages[stage]);Text("B$%.2f".format(order.total));if(order.deliveryLocation.isNotBlank())Text("📍 ${order.deliveryLocation}")}}}
@Composable fun DeliveredOrderCard(order:Order,language:String){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("#${order.id}",fontWeight=FontWeight.Bold);Text(if(order.delivery=="Pickup")tr(language,"✅ Pickup selesai","✅ Pickup complete")else tr(language,"✅ Delivery sampai","✅ Delivered"));Text("B$%.2f".format(order.total))}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun HistoryDetailSheet(order:Order,onClose:()->Unit,language:String){ModalBottomSheet(onDismissRequest=onClose){Column(Modifier.padding(20.dp)){Text(tr(language,"Detail History","History Details"),style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);order.lines.forEach{Text("• ${it.product.name} × ${it.qty}")};if(order.deliveryLocation.isNotBlank())Text("📍 ${order.deliveryLocation}")}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun CustomerServiceSheet(onClose:()->Unit,language:String){ModalBottomSheet(onDismissRequest=onClose){Column(Modifier.padding(24.dp)){Text("💬 KadaiKu Customer Service",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(tr(language,"Ada masalah dengan order, seller atau delivery? Hubungi customer service KadaiKu.","Having an issue with an order, seller or delivery? Contact KadaiKu customer service."));Text("📞 +673 7XX XXXX")}}}

fun startOfWeek(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_WEEK,firstDayOfWeek);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}
fun startOfMonth(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_MONTH,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}
fun startOfYear(now:Long):Long{val c=Calendar.getInstance().apply{timeInMillis=now;set(Calendar.DAY_OF_YEAR,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};return c.timeInMillis}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun SellerSheet(onClose:()->Unit,onAdd:()->Unit,products:List<Product>,orders:List<Order>,profile:SellerProfile,sellerId:String,onDelete:(String)->Unit,language:String){val sellerOrders=orders.filter{o->o.lines.any{it.product.sellerId==sellerId}};val active=sellerOrders.filter{it.deliveredAt==null};val history=sellerOrders.filter{it.deliveredAt!=null};ModalBottomSheet(onDismissRequest=onClose){LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("${profile.shop} Dashboard",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("📞 ${profile.phone}");Text("📍 ${profile.address}")};item{Button(onAdd,Modifier.fillMaxWidth()){Text(tr(language,"+ Tambah Produk","+ Add Product"))}};item{Text(tr(language,"Produk saya / Stok","My Products / Stock"),fontWeight=FontWeight.Bold)};items(products.filter{it.sellerId==sellerId}){p->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(10.dp)){Column(Modifier.weight(1f)){Text(p.name);Text("${tr(language,"Stok","Stock")}: ${p.stock}")};TextButton({onDelete(p.id)}){Text(tr(language,"Padam","Delete"))}}}};item{Text(tr(language,"Order Aktif","Active Orders"),fontWeight=FontWeight.Bold)};items(active){o->Text("#${o.id} • B$%.2f".format(sellerOrderValue(o,sellerId)))};item{Text(tr(language,"History Seller","Seller History"),fontWeight=FontWeight.Bold)};items(history){o->Text("#${o.id} • ✅ ${tr(language,"Selesai","Complete")}")}}}}
@Composable fun StatCard(label:String,count:Int,sales:Double,m:Modifier=Modifier){Card(m){Column(Modifier.padding(10.dp)){Text(label);Text("$count");Text("B$%.2f".format(sales))}}}
@Composable fun AddProductDialog(sellerProfile:SellerProfile,onDismiss:()->Unit,onSave:(String,Double,String,String,Int)->Unit,language:String){var n by remember{mutableStateOf("")};var pr by remember{mutableStateOf("")};var cat by remember{mutableStateOf("Makanan")};var stock by remember{mutableStateOf("")};var imageUri by remember{mutableStateOf("")};val launcher=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri:Uri?->imageUri=uri?.toString().orEmpty()};AlertDialog(onDismissRequest=onDismiss,title={Text(tr(language,"Tambah Produk","Add Product"))},text={Column{OutlinedButton({launcher.launch("image/*")},Modifier.fillMaxWidth()){Text(tr(language,"Pilih gambar dari Gallery","Choose image from Gallery"))};OutlinedTextField(n,{n=it},label={Text(tr(language,"Nama produk","Product name"))});OutlinedTextField(pr,{pr=it},label={Text(tr(language,"Harga B$","Price B$"))});OutlinedTextField(stock,{stock=it.filter{ch->ch.isDigit()}},label={Text(tr(language,"Jumlah stok","Stock quantity"))});OutlinedTextField(cat,{cat=it},label={Text(tr(language,"Kategori","Category"))});Text("📍 ${sellerProfile.address}")}},confirmButton={Button(enabled=n.isNotBlank()&&pr.toDoubleOrNull()!=null&&stock.toIntOrNull()?.let{it>0}==true&&imageUri.isNotBlank(),onClick={onSave(n,pr.toDouble(),cat,imageUri,stock.toInt())}){Text(tr(language,"Simpan","Save"))}},dismissButton={TextButton(onDismiss){Text(tr(language,"Batal","Cancel"))}})}